export const Routes = {
  MAIN_NAVIGATOR: 'MAIN_NAVIGATOR',

  AUTH_NAVIGATOR: 'AUTH_NAVIGATOR',

  BOTTOM_TAB_BAR_NAVIGATOR: 'BOTTOM_TAB_BAR_NAVIGATOR',

  ALERTS_NAVIGATOR: 'ALERTS_NAVIGATOR',

  PROFILE_NAVIGATOR: 'PROFILE_NAVIGATOR',

  AUTH: 'AUTH',

  PROFILE: 'PROFILE',

  ALERTS: 'ALERTS',
} as const;
