import { Test, testEndpointQuery } from './models';

const QUERY_KEYS = {
  TEST_QUERY_AUTH_SERVICE: 'TEST_QUERY_AUTH_SERVICE',
  TEST_INFINITE_QUERY_AUTH_SERVICE: 'TEST_INFINITE_QUERY_AUTH_SERVICE',
  TEST_SUSPENSE_QUERY_AUTH_SERVICE: 'TEST_SUSPENSE_QUERY_AUTH_SERVICE',
  TEST_SUSPENSE_INFINITE_QUERY_AUTH_SERVICE:
    'TEST_SUSPENSE_INFINITE_QUERY_AUTH_SERVICE',
  TEST_QUERIES_AUTH_SERVICE: 'TEST_QUERIES_AUTH_SERVICE',
  TEST_PREFETCH_AUTH_SERVICE: 'TEST_PREFETCH_AUTH_SERVICE',
  TEST_PREFETCH_INFINITE_QUERY_AUTH_SERVICE:
    'TEST_PREFETCH_INFINITE_QUERY_AUTH_SERVICE',
  TEST_QUERY_WITH_CUSTOM_CLIENT_AUTH_SERVICE:
    'TEST_QUERY_WITH_CUSTOM_CLIENT_AUTH_SERVICE',
  TEST_QUERY_WITH_FETCH_AUTH_SERVICE: 'TEST_QUERY_WITH_FETCH_AUTH_SERVICE',
  TEST_VOID_REQUEST_AUTH_SERVICE: 'TEST_VOID_REQUEST_AUTH_SERVICE',
  TEST_SPECIAL_REQUEST_AUTH_SERVICE: 'TEST_SPECIAL_REQUEST_AUTH_SERVICE',
  TEST_ENDPOINT_QUERY_AUTH_SERVICE: 'TEST_ENDPOINT_QUERY_AUTH_SERVICE',
  TEST_MUTATION_AUTH_SERVICE: 'TEST_MUTATION_AUTH_SERVICE',
  TEST_ENDPOINT_MUTATION_AUTH_SERVICE: 'TEST_ENDPOINT_MUTATION_AUTH_SERVICE',
} as const;

export const AUTH_QUERY_KEYS = {
  testQueryAuthService: (params: Test) =>
    [QUERY_KEYS.TEST_QUERY_AUTH_SERVICE, params] as const,
  testInfiniteQueryAuthService: (params: Test) =>
    [QUERY_KEYS.TEST_INFINITE_QUERY_AUTH_SERVICE, params] as const,
  testSuspenseQueryAuthService: (params: Test) =>
    [QUERY_KEYS.TEST_SUSPENSE_QUERY_AUTH_SERVICE, params] as const,
  testSuspenseInfiniteQueryAuthService: (params: Test) =>
    [QUERY_KEYS.TEST_SUSPENSE_INFINITE_QUERY_AUTH_SERVICE, params] as const,
  testQueriesAuthService: (params: Test) =>
    [QUERY_KEYS.TEST_QUERIES_AUTH_SERVICE, params] as const,
  testPrefetchAuthService: (params: Test) =>
    [QUERY_KEYS.TEST_PREFETCH_AUTH_SERVICE, params] as const,
  testPrefetchInfiniteQueryAuthService: (params: Test) =>
    [QUERY_KEYS.TEST_PREFETCH_INFINITE_QUERY_AUTH_SERVICE, params] as const,
  testQueryWithCustomClientAuthService: (params: Test) =>
    [QUERY_KEYS.TEST_QUERY_WITH_CUSTOM_CLIENT_AUTH_SERVICE, params] as const,
  testQueryWithFetchAuthService: (params: Test) =>
    [QUERY_KEYS.TEST_QUERY_WITH_FETCH_AUTH_SERVICE, params] as const,
  testVoidRequestAuthService: () =>
    [QUERY_KEYS.TEST_VOID_REQUEST_AUTH_SERVICE] as const,
  testSpecialRequestAuthService: () =>
    [QUERY_KEYS.TEST_SPECIAL_REQUEST_AUTH_SERVICE] as const,
  testEndpointQueryAuthService: (params: testEndpointQuery) =>
    [QUERY_KEYS.TEST_ENDPOINT_QUERY_AUTH_SERVICE, params] as const,
  testMutationAuthService: () =>
    [QUERY_KEYS.TEST_MUTATION_AUTH_SERVICE] as const,
  testEndpointMutationAuthService: () =>
    [QUERY_KEYS.TEST_ENDPOINT_MUTATION_AUTH_SERVICE] as const,
};
