import { Test } from './models';

const QUERY_KEYS = {
  GET_USER_AUTH_SERVICE: 'GET_USER_AUTH_SERVICE',
  GET_USER_PREFETCH_AUTH_SERVICE: 'GET_USER_PREFETCH_AUTH_SERVICE',
  GET_USER_PAGINATE_AUTH_SERVICE: 'GET_USER_PAGINATE_AUTH_SERVICE',
  GET_USER_PREFETCH_PAGINATE_AUTH_SERVICE:
    'GET_USER_PREFETCH_PAGINATE_AUTH_SERVICE',
  POST_USER_AS_QUERY_AUTH_SERVICE: 'POST_USER_AS_QUERY_AUTH_SERVICE',
} as const;

export const AUTH_QUERY_KEYS = {
  GET_USER_AUTH_SERVICE: (params: Test) =>
    [QUERY_KEYS.GET_USER_AUTH_SERVICE, params] as const,
  GET_USER_PREFETCH_AUTH_SERVICE: (params: Test) =>
    [QUERY_KEYS.GET_USER_PREFETCH_AUTH_SERVICE, params] as const,
  GET_USER_PAGINATE_AUTH_SERVICE: (params: Test) =>
    [QUERY_KEYS.GET_USER_PAGINATE_AUTH_SERVICE, params] as const,
  GET_USER_PREFETCH_PAGINATE_AUTH_SERVICE: (params: Test) =>
    [QUERY_KEYS.GET_USER_PREFETCH_PAGINATE_AUTH_SERVICE, params] as const,
  POST_USER_AS_QUERY_AUTH_SERVICE: (params: Test) =>
    [QUERY_KEYS.POST_USER_AS_QUERY_AUTH_SERVICE, params] as const,
};
