name: Deploy to Development (iOS)

on:
  push:
    branches:
      - develop

jobs:
  build-develop-ios:
    name: Build & Upload iOS App (Development)
    runs-on: macos-14

    steps:
      - name: Select Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Enable Corepack and Set Yarn Version
        run: |
          corepack enable
          corepack prepare yarn@latest --activate
          yarn set version 4.6.0
          yarn --version

      - name: Install node modules
        run: yarn install
        env:
          CI: true

      - name: Decode base64 .env file from secrets
        uses: akiojin/decode-base64-github-action@v0.1.0
        id: decode-base64
        with:
          base64: ${{ secrets.DEV_APPLICATION_ENV }}
          output-path: ${{ runner.temp }}/.env

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler: 2.3.7
          bundler-cache: true

      - name: Install Fastlane dependencies
        run: |
          cd ios
          bundle install
        env:
          CI: true

      - name: Install Fastlane plugins
        run: |
          cd ios
          bundle exec fastlane install_plugins
        env:
          CI: true

      - name: Build and Upload to App Store (TestFlight)
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: "deploy_to_testflight"
          subdirectory: "ios"
        env:
          APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
          APPLE_KEY_CONTENT: ${{ secrets.APPLE_KEY_CONTENT }}
          APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
          APP_STORE_CONNECT_TEAM_ID: ${{ secrets.APP_STORE_CONNECT_TEAM_ID }}
          DEVELOPER_APP_ID: ${{ secrets.DEVELOPER_APP_ID }}
          DEVELOPER_APP_IDENTIFIER: ${{ secrets.DEVELOPER_APP_IDENTIFIER }}
          DEVELOPER_PORTAL_TEAM_ID: ${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          PROVISIONING_PROFILE_SPECIFIER: ${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}
          GIT_AUTHORIZATION: ${{ secrets.GIT_AUTHORIZATION }}
          IOS_VERSION_NUMBER: ${{ secrets.IOS_VERSION_NUMBER }}
